MoveTutor_Text_SwaggerGift: @ 82C6E37
	.string "Heh! My POKéMON totally rules!\n"
	.string "It's cooler than any POKéMON!\p"
	.string "I was lipping off with a swagger in\n"
	.string "my step like that when the CHAIRMAN\l"
	.string "chewed me out.\p"
	.string "That took the swagger out of my step.\p"
	.string "Here, I guess I won't be needing\n"
	.string "this anymore.$"

MoveTutor_Text_SwaggerReceived: @ 82C6F9E
	.string "I'll just praise my POKéMON from now\n"
	.string "on without the swagger.$"

MoveTutor_Text_SmackDownGift: @ 82C6FDB
	.string "Did you know that FLYING-type\n"
	.string "POKéMON or POKéMON with LEVITATE\l"
	.string "are immune to GROUND-type moves?\p"
	.string "Well, what if there was a way to\n"
	.string "knock them out of the air?\p"
	.string "Here, give this TM a shot!$"

MoveTutor_Text_SmackDownReceived: @ 82C7133
	.string "Knock those airborne POKéMON to\n"
	.string "the ground, then hit 'em with a\l"
	.string "strong GROUND-type move!$"

MoveTutor_Text_EchoedVoiceGift: @ 82C7174
	.string "There's a move that gets stronger\n"
	.string "when you keep using it in a row.\p"
	.string "It's a NORMAL-type move, and it is\n"
	.string "wickedly cool.\p"
	.string "It's called ECHOED VOICE.\n"
	.string "Why don't you try it out?$"

MoveTutor_Text_EchoedVoiceReceived: @ 82C726E
	.string "I get a thrill watching the move\n"
	.string "getting stronger and stronger!$"

MoveTutor_NaturePowerGift: @ 82C72B6
	.string "Ah, young one!\p"
	.string "I see you've travelled very far, and\n"
	.string "through many of the natural\l"
	.string "environments the make up HOENN.\p"
	.string "Your POKéMON can harness the power\n"
	.string "of nature in battle to perform attacks\l"
	.string "of various types and power with this.$"

MoveTutor_Text_NaturePowerReceived: @ 82C73F6
	.string "HOENN is beautiful region.\p"
	.string "Let your POKéMON embrace its\n"
	.string "natural power!$"

MoveTutor_Text_SmartStrikeGift: @ 82C7449
	.string "I love X ACCURACY! The idea of never\n"
	.string "missing an attack got me so excited\l"
	.string "that I bought the MART's entire stock!\p"
	.string "Only after my purchase did I learn\n"
	.string "that there are moves that never miss…\p"
	.string "Don't make the same mistake as me,\n"
	.string "save your money and just use this TM.$"

MoveTutor_Text_SmartStrikeReceived: @ 82C75B5
	.string "If you want to buy some X ACCURACY\n"
	.string "then you'll have to visit another\l"
	.string "POKé MART. Sorry!$"

MoveTutor_Text_SleepTalkGift: @ 82C7637
	.string "Humph! My wife relies on HIDDEN\n"
	.string "POWER to stay awake.\p"
	.string "She should just take a nap like I do,\n"
	.string "and SLEEP TALK.\p"
	.string "Why don't you let your POKéMON take\n"
	.string "a nap, too?$"

MoveTutor_Text_SleepTalkReceived: @ 82C775A
	.string "I've never once gotten my wife's\n"
	.string "coin trick right.\p"
	.string "I would be happy if I got it right\n"
	.string "even as I SLEEP TALK…$"

MoveTutor_Text_SubstituteGift: @ 82C77C6
	.string "When I see the wide world from up\n"
	.string "here on the roof…\p"
	.string "I think about how nice it would be\n"
	.string "if there were more than just one me\l"
	.string "so I could enjoy all sorts of lives.\p"
	.string "Of course it's not possible.\n"
	.string "Giggle…\p"
	.string "However, your POKéMON may be able to\n"
	.string "get close by creating a SUBSTITUTE.$"

MoveTutor_Text_SubstituteReceived: @ 82C794B
	.string "We human beings should enjoy our\n"
	.string "own lives to the utmost!\p"
	.string "I hope you'll get that way, too!$"

MoveTutor_Text_PowerUpPunchGift: @ 82C79A6
	.string "I can't do this anymore!\p"
	.string "It's utterly hopeless!\p"
	.string "I'm a FIGHTING-type TRAINER,\n"
	.string "so I can't win at the MOSSDEEP GYM\l"
	.string "no matter how hard I try!\p"
	.string "Argh! Punch! Punch! Punch!\n"
	.string "Punch! Punch! Punch!\p"
	.string "What, don't look at me that way!\n"
	.string "I'm only hitting the ground!\p"
	.string "Maybe you'll have better luck than\n"
	.string "I did. Take this.$"

MoveTutor_Text_PowerUpPunchReceived: @ 82C7B4F
	.string "I want you to win at the Mossdeep Gym\n"
	.string "using that PowerUpPunch!$"

MoveTutor_Text_SwordsDanceGift: @ 82C7B8E
	.string "Sigh…\p"
	.string "Sootopilis's Gym Leader is really\n"
	.string "lovably admirable.\p"
	.string "But that also means I have many\n"
	.string "rivals for his attention.\p"
	.string "I couldn't even catch his eye, even\n"
	.string "with my frenetic dancing.\p"
	.string "My dance can't help with my love\n"
	.string "life, but maybe it can help your\l"
	.string "POKéMON in battle.$"

MoveTutor_Text_SwordsDanceReceived: @ 82C7CC8
	.string "I won't live for love anymore!\n"
	.string "I'll become tough!$"

MoveTutor_Text_ExplosionGift: @ 82C7CFA
	.string "I don't intend to be going nowhere\n"
	.string "fast in the sticks like this forever.\p"
	.string "You watch me, I'll get out to the city\n"
	.string "and become a huge hit.\p"
	.string "Seriously, I'm going to cause\n"
	.string "a huge EXPLOSION of popularity!\p"
	.string "Take this TM. With it, your POKéMON\n"
	.string "can cause an EXPLOSION in battle!$"

MoveTutor_Text_ExplosionReceived: @ 82C7E7A
	.string "For a long time, I've taught POKéMON\n"
	.string "how to use EXPLOSION, but I've yet\l"
	.string "to ignite my own EXPLOSION…\p"
	.string "Maybe it's because deep down,\n"
	.string "I would rather stay here…$"
